from telethon import events
import subprocess
import asyncio
import time


@command(pattern="^.cmds", outgoing=True)
async def install(event):
    OUTPUT = f"**ℹ️ LISTA PLUG-IN 🔍:**\n ├─── .afk Quando vuoi prendere una pausa...\n ├─── .alive Controlla lo stato del bot \n ├─── .blacklist \n ├─── .bye Abbandona una chat con stile 😏 \n ├─── .karb (testo*) Un semplice Text to Image \n ├─── .coronavirus (paese*) Informazioni coronavirus su un paese \n  ├─── .significato (parola*) \n ├─── .emoji Digita .help emoji. Animazione emoji \n  ├─── .figlet (testo*) Figlet text to ascii \n  ├─── .filters Digita .help filter. Utilizza filtri al quale il bot risponderà \n ├─── .fuck 🖕 \n ├─── .gbun Fake Ban \n  ├─── .get_admin Lista Admin \n ├─── .get_bot Lista Bot \n ├─── .get_id Ottieni l'ID della chat \n ├─── .song (nomecanzone*) Invia una canzone \n ├─── .gmute (tag/rispondi*) Muta Globalmente \n ├─── .github (username*) \n ├─── .google (query) \n ├─── .google image (query*) \n ├─── .hack Hackera il mondo 👾 \n\n ├─── .sega \n ├─── .harrypotter 🎩 \n ├─── .hypno Ipnotizza facilmente con un comando \n ├─── .img (query*) Cra un immagine dal web \n ├─── .info (rispondi/tag*) Tutte le info su un utente \n ├─── .install (rispondi a un plugin*) Installa plugin esterni \n ├─── .lock (msg(media/audio/sticker/gamee/ainline/adduser/cpin/changeinfo*) Blocca cosa non vuoi in una chat \n ├─── .lol \n ├─── .lucky Se vuoi regalare questo userbot \n ├─── .mmf (testo ; testo*) Memify all images \n ├─── .luna /.sluna \n ├─── .mute Muta uno che parla troppo \n ├─── .macos / .windows / .linux / .stock \n ├─── .padmin Diventa dmin dappertutto 1n ├─── .pula Chiama la polizia \n ├─── .restart Riavvi il bot \n ├─── .profile Digita .help profile per info \n ├─── .purge (rispondi*) Elimina fino al messaggio a cui si risponde \n ├─── .quotly (rispondi*) \n ├─── .sangamata Digita .help sangamata per info \n ├─── .scam (azione*) Fai finta di eseguire un azioneper un tempo determinato (scrivere inviare foto ecc..) \n ├─── .screencaputure (*url*) Fa screen di un sito senza aprirlo \n ├─── .snake \n ├─── .spam (testo*) (1-99*) 1n ├─── .stickers Digita .help stickers per info \n ├─── .tagall Tagga tutti gli utenti \n ├─── .telegraph (media/testo*) \n ├─── .tr (IT italiano / EN inglese*) (testo/rispondi*) Traduce messaggi [CODICI LINGUA](https://www.science.co.il/language/Codes.php) \n ├─── .tts (testo) Text to Speech \n ├─── .webupload (ripsondi*) (anonfiles|transfer|filebin|anonymousfiles|megaupload|bayfiles) \n ├─── .welcome Digita .help welcome per info \n └─── .yta/.ytv (url*) Scarica video o audio da youtube yta = audio ytv = video \n\n**ℹ️ SUGGERIMENTO:** __Per vedere i comandi di un plug-in, fai:-__ \n `.help <plugin name>` **senza le parentesi < >.** \n **Oppure Contatta @AnonHexo**"
    await event.edit(OUTPUT)
